\documentclass{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}


\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item A group of researchers is running an experiment over the course of 30 months, 
with a single observation collected at the end of each month. Let $X_1, ..., X_{30}$
denote the observations for each month. From prior studies, the researchers know that
\[X_i \sim f_X(x),\]
but the mean $\mu_X$ is unknown, and they wish to conduct the following test
\begin{align*}
H_0&: \mu_X = 0\\
H_a&: \mu_X > 0.
\end{align*}
At month $k$, they have accumulated data $X_1, ..., X_k$ and they have the 
$t$-statistic
\[T_k = \frac{\bar{X} - 0}{S_k/\sqrt{n}}.\]
The initial plan was to test the hypotheses after all data was collected (at the 
end of month 30), at level $\alpha=0.05$. However, conducting the experiment is 
expensive, so the researchers want to ``peek" at the data at the end of month 20 
to see if they can stop it early. That is, the researchers propose to check 
whether $t_{20}$ provides statistically discernible support for the alternative. 
If it does, they will stop the experiment early and report support for the 
researcher's alternative hypothesis. If it does not, they will continue to month 
30 and test whether $t_{30}$ provides statistically discernible support for the
alternative.

\begin{enumerate}
  \item What values of $t_{20}$ provide statistically discernible support for the
  alternative hypothesis?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(t20.value} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.95}\hldef{,} \hlkwc{df} \hldef{=} \hlnum{20}\hlopt{-}\hlnum{1}\hldef{))}
\end{alltt}
\begin{verbatim}
## [1] 1.729133
\end{verbatim}
\end{kframe}
\end{knitrout}
All $t_{20}$ values greater than or equal to 1.729133 provide statistically discernible support for the
  alternative hypothesis.
  \item What values of $t_{30}$ provide statistically discernible support for the
  alternative hypothesis?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(t30.value} \hlkwb{<-} \hlkwd{qt}\hldef{(}\hlnum{0.95}\hldef{,} \hlkwc{df} \hldef{=} \hlnum{30}\hlopt{-}\hlnum{1}\hldef{))}
\end{alltt}
\begin{verbatim}
## [1] 1.699127
\end{verbatim}
\end{kframe}
\end{knitrout}
All $t_{30}$ values greater than or equal to 1.699127 provide statistically discernible support for the
  alternative hypothesis.
  \item Suppose $f_X(x)$ is a Laplace distribution with $a=0$ and $b=4.0$.
  Conduct a simulation study to assess the Type I error rate of this approach.\\
  \textbf{Note:} You can use the \texttt{rlaplace()} function from the \texttt{VGAM}
  package for \texttt{R} \citep{VGAM}.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hldef{(VGAM)}
\hldef{a} \hlkwb{=} \hlnum{0}
\hldef{b} \hlkwb{=} \hlnum{4.0}
\hldef{type1.20} \hlkwb{<-} \hlnum{0}
\hldef{type1.30} \hlkwb{<-} \hlnum{0}
\hldef{no.error} \hlkwb{<-} \hlnum{0}

\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hlnum{10000}\hldef{)\{}
  \hldef{simulations} \hlkwb{<-} \hlkwd{rlaplace}\hldef{(}\hlkwc{n} \hldef{=} \hlnum{30}\hldef{,} \hlkwc{location} \hldef{= a,} \hlkwc{scale} \hldef{= b)}

  \hldef{t} \hlkwb{<-} \hlkwd{t.test}\hldef{(simulations[}\hlnum{1}\hlopt{:}\hlnum{20}\hldef{],}
              \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
              \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{)}

  \hlcom{# Outcome 1:}
  \hlkwa{if} \hldef{(t}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)\{}
    \hldef{type1.20} \hlkwb{<-} \hldef{type1.20} \hlopt{+} \hlnum{1}
  \hldef{\}} \hlkwa{else} \hldef{\{}
    \hlcom{# Outcome 2: }
    \hldef{t2} \hlkwb{<-} \hlkwd{t.test}\hldef{(simulations[}\hlnum{1}\hlopt{:}\hlnum{30}\hldef{],}
                 \hlkwc{mu} \hldef{=} \hlnum{0}\hldef{,}
                 \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{)}

    \hlkwa{if} \hldef{(t2}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)\{}
      \hldef{type1.30} \hlkwb{<-} \hldef{type1.30} \hlopt{+} \hlnum{1}
    \hldef{\}} \hlkwa{else} \hldef{\{}
      \hlcom{# Outcome 3:}
      \hldef{no.error} \hlkwb{<-} \hldef{no.error} \hlopt{+} \hlnum{1}
    \hldef{\}}
  \hldef{\}}
\hldef{\}}
\hldef{(errors.20} \hlkwb{<-} \hldef{type1.20}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0475
\end{verbatim}
\begin{alltt}
\hldef{(errors.30} \hlkwb{<-} \hldef{type1.30}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0258
\end{verbatim}
\begin{alltt}
\hldef{(no.errors} \hlkwb{<-} \hldef{no.error}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.9267
\end{verbatim}
\begin{alltt}
\hldef{(type1.error} \hlkwb{<-} \hldef{(type1.20} \hlopt{+} \hldef{type1.30)}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0733
\end{verbatim}
\end{kframe}
\end{knitrout}
The type one error rate at the end of 20 months is about 0.05 Looking at the type one error between 20 and 30 months, it decreases to about 0.025 Overall, the type one error rate from 0 months to 30 months is about 0.075, leaving the rate of not getting a type one error to be about 0.925.

\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item Perform a simulation study to assess the robustness of the $T$ test. 
  Specifically, generate samples of size $n=15$ from the Beta(10,2), Beta(2,10), 
  and Beta(10,10) distributions and conduct the following hypothesis tests against 
  the actual mean for each case (e.g., $\frac{10}{10+2}$, $\frac{2}{10+2}$, and 
  $\frac{10}{10+10}$).
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{# sample size}
\hldef{n} \hlkwb{<-} \hlnum{15}
\hlcom{# true mean for Beta(10,2)}
\hldef{mean.10.2} \hlkwb{<-} \hlnum{10}\hlopt{/}\hldef{(}\hlnum{10}\hlopt{+}\hlnum{2}\hldef{)}
\hlcom{# true mean for Beta(2,10)}
\hldef{mean.2.10} \hlkwb{<-} \hlnum{2}\hlopt{/}\hldef{(}\hlnum{2}\hlopt{+}\hlnum{10}\hldef{)}
\hlcom{# true mean for Beta(10,10)}
\hldef{mean.10.10} \hlkwb{<-} \hlnum{10}\hlopt{/}\hldef{(}\hlnum{10}\hlopt{+}\hlnum{10}\hldef{)}
\hlcom{# will loop over and add to}
\hldef{left_tail} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{0}\hldef{,}\hlnum{0}\hldef{)}
\hldef{right_tail} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{0}\hldef{,}\hlnum{0}\hldef{)}
\hldef{two_tail} \hlkwb{<-} \hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{0}\hldef{,}\hlnum{0}\hldef{)}
\hlcom{# start loop}
\hlkwa{for} \hldef{(i} \hlkwa{in} \hlnum{1}\hlopt{:}\hlnum{10000}\hldef{)\{}
  \hldef{beta1} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlnum{10}\hldef{,} \hlnum{2}\hldef{)}
  \hldef{beta2} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlnum{2}\hldef{,} \hlnum{10}\hldef{)}
  \hldef{beta3} \hlkwb{<-} \hlkwd{rbeta}\hldef{(n,} \hlnum{10}\hldef{,} \hlnum{10}\hldef{)}
\hlcom{# part (a): What proportion of the time do we make an error of Type I for a left-tailed test?}
  \hlcom{# Left-Tailed Test}
  \hldef{left.10.2} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta1,}
                  \hlkwc{mu} \hldef{= mean.10.2,}
                  \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{)}
  \hldef{left.2.10} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta2,}
                  \hlkwc{mu} \hldef{= mean.2.10,}
                  \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{)}
  \hldef{left.10.10} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta3,}
                  \hlkwc{mu} \hldef{= mean.10.10,}
                  \hlkwc{alternative} \hldef{=} \hlsng{"less"}\hldef{)}
  \hlcom{# Keeping track of type 1 errors for each distribution}
  \hldef{left_tail[}\hlnum{1}\hldef{]} \hlkwb{<-} \hldef{left_tail[}\hlnum{1}\hldef{]} \hlopt{+} \hldef{(left.10.2}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
  \hldef{left_tail[}\hlnum{2}\hldef{]} \hlkwb{<-} \hldef{left_tail[}\hlnum{2}\hldef{]} \hlopt{+} \hldef{(left.2.10}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
  \hldef{left_tail[}\hlnum{3}\hldef{]} \hlkwb{<-} \hldef{left_tail[}\hlnum{3}\hldef{]} \hlopt{+} \hldef{(left.10.10}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
\hlcom{# part (b): What proportion of the time do we make an error of Type I for a right-tailed test?}
  \hlcom{# Left-Tailed Test}
  \hldef{right.10.2} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta1,}
                      \hlkwc{mu} \hldef{= mean.10.2,}
                      \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{)}
  \hldef{right.2.10} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta2,}
                      \hlkwc{mu} \hldef{= mean.2.10,}
                      \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{)}
  \hldef{right.10.10} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta3,}
                       \hlkwc{mu} \hldef{= mean.10.10,}
                       \hlkwc{alternative} \hldef{=} \hlsng{"greater"}\hldef{)}
  \hlcom{# Keeping track of type 1 errors for each distribution}
  \hldef{right_tail[}\hlnum{1}\hldef{]} \hlkwb{<-} \hldef{right_tail[}\hlnum{1}\hldef{]} \hlopt{+} \hldef{(right.10.2}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
  \hldef{right_tail[}\hlnum{2}\hldef{]} \hlkwb{<-} \hldef{right_tail[}\hlnum{2}\hldef{]} \hlopt{+} \hldef{(right.2.10}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
  \hldef{right_tail[}\hlnum{3}\hldef{]} \hlkwb{<-} \hldef{right_tail[}\hlnum{3}\hldef{]} \hlopt{+} \hldef{(right.10.10}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
\hlcom{# part (c): What proportion of the time do we make an error of Type I for a two-tailed test?}
  \hlcom{# Left-Tailed Test}
  \hldef{two_tail.10.2} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta1,}
                       \hlkwc{mu} \hldef{= mean.10.2,}
                       \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}
  \hldef{two_tail.2.10} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta2,}
                       \hlkwc{mu} \hldef{= mean.2.10,}
                       \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}
  \hldef{two_tail.10.10} \hlkwb{<-} \hlkwd{t.test}\hldef{(beta3,}
                        \hlkwc{mu} \hldef{= mean.10.10,}
                        \hlkwc{alternative} \hldef{=} \hlsng{"two.sided"}\hldef{)}
  \hlcom{# Keeping track of type 1 errors for each distribution}
  \hldef{two_tail[}\hlnum{1}\hldef{]} \hlkwb{<-} \hldef{two_tail[}\hlnum{1}\hldef{]} \hlopt{+} \hldef{(two_tail.10.2}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
  \hldef{two_tail[}\hlnum{2}\hldef{]} \hlkwb{<-} \hldef{two_tail[}\hlnum{2}\hldef{]} \hlopt{+} \hldef{(two_tail.2.10}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
  \hldef{two_tail[}\hlnum{3}\hldef{]} \hlkwb{<-} \hldef{two_tail[}\hlnum{3}\hldef{]} \hlopt{+} \hldef{(two_tail.10.10}\hlopt{$}\hldef{p.value} \hlopt{<} \hlnum{0.05}\hldef{)}
\hldef{\}}
\hlcom{# part (a): What proportion of the time do we make an error of Type I for a left-tailed test?}
\hldef{(type1.error.left} \hlkwb{<-} \hldef{left_tail}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0283 0.0830 0.0496
\end{verbatim}
\begin{alltt}
\hlcom{# part (b): What proportion of the time do we make an error of Type I for a right-tailed test?}
\hldef{(type1.error.right} \hlkwb{<-} \hldef{right_tail}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0765 0.0301 0.0512
\end{verbatim}
\begin{alltt}
\hlcom{# part (c): What proportion of the time do we make an error of Type I for a two-tailed test?}
\hldef{(type1.error.two_sided} \hlkwb{<-} \hldef{two_tail}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0564 0.0655 0.0509
\end{verbatim}
\end{kframe}
\end{knitrout}
  
  \begin{enumerate}
    \item What proportion of the time do we make an error of Type I for a
    left-tailed test?
Using a left-tailed test, we make a type one error for the Beta(10,2) distribution at about a rate of 0.03, at about a rate of 0.08 for the Beta(2,10) distribution, and at about a rate of 0.05 for the beta(10,10) distribution.
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(type1.error.left} \hlkwb{<-} \hldef{left_tail}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0283 0.0830 0.0496
\end{verbatim}
\end{kframe}
\end{knitrout}
    \item What proportion of the time do we make an error of Type I for a
    right-tailed test?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(type1.error.right} \hlkwb{<-} \hldef{right_tail}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0765 0.0301 0.0512
\end{verbatim}
\end{kframe}
\end{knitrout}
Using a right-tailed test, we make a type one error for the Beta(10,2) distribution at a rate of about 0.08, at a rate of 0.03 for the Beta(2,10) distribution, and at a rate of about 0.05 for the beta(10,10) distribution.
    \item What proportion of the time do we make an error of Type I for a
    two-tailed test?
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{(type1.error.two_sided} \hlkwb{<-} \hldef{two_tail}\hlopt{/}\hlnum{10000}\hldef{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0564 0.0655 0.0509
\end{verbatim}
\end{kframe}
\end{knitrout}
Using a two-tailed test, we make a type one error for the Beta(10,2) distribution at a rate of about 0.06, at a rate of about 0.06 for the Beta(2,10) distribution, and at a rate of about 0.05 for the beta(10,10) distribution.
    \item How does skewness of the underlying population distribution effect
    Type I error across the test types?

% latex table generated in R 4.4.2 by xtable 1.8-4 package
% Tue Apr 22 17:03:23 2025
\begin{table}[H]
\centering
\begingroup\small
\begin{tabular}{lrrr}
  \hline
Distribution & Left-Tailed Test & Right-Tailed Test & Two-Tailed Test \\ 
  \hline
Beta(10,2) & 0.03 & 0.08 & 0.06 \\ 
  Beta(2,10) & 0.08 & 0.03 & 0.07 \\ 
  Beta(10,10) & 0.05 & 0.05 & 0.05 \\ 
   \hline
\end{tabular}
\endgroup
\caption{Type 1 Error Rate Comparison} 
\end{table}

We can see from the table that the Beta(10,10) distribution, which is symmetric or not skewed, has similar rates of type one errors across all three tests. However, the skewed beta distributions have varying rates of type one errors across the tests. The Beta(10,2) distribution is left-tailed, so it has a lower rate of type one errors with a left-tailed test as opposed to with a right-tailed test. Since the Beta(2,10) distribution is right-tailed, it has a lower rate of type one errors with a right-tailed test as opposed to with a left-tailed test. When a two-tailed test is used, both distributions report similar rates of type 1 error.
  \end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End Document
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{enumerate}
\bibliography{bibliography}
\end{document}
